Some miscellaneous fixes and additions
n2o/url-shortener pull request #21
Opened 2020-01-30 18:45 UTC by iTitus

The new images are:

----

Index:
![shorty_index](https://user-images.githubusercontent.com/5154317/73479713-c193cb80-4398-11ea-9e81-48f891a230d7.png)

----

Admin:
![shorty_admin](https://user-images.githubusercontent.com/5154317/73479722-c6f11600-4398-11ea-8c48-fcf3bcebc8cd.png)

2020-01-30 20:48 UTC, Segelzwerg approved these changes

2020-01-31 09:24 UTC, n2o commented
Hm, i still like my landing page image, which is in the repository. Put into the browser makes it look like a real application and not just like a flat image. So please let my original image in the README and we do not need additional images for the Login Page.

2020-01-31 09:27 UTC, n2o requested changes
* Keep old image 
* Remove the new images

Thank you!

2020-01-31 09:27 UTC, n2o commented on README.adoc
> -image::img/shorty.png[shorty]
Please leave the old image here

2020-01-31 09:27 UTC, n2o commented on README.adoc
> +image::img/shorty_admin.png[shorty admin panel]
```suggestion
```

2020-01-31 09:27 UTC, n2o commented on README.adoc
> +image::img/shorty_index.png[shorty index]
```suggestion
```

2020-01-31 09:40 UTC, n2o commented
Please add in the next time a more descriptive title 😬 

This closes #19

2020-01-31 10:35 UTC, iTitus commented
Can you make a new image of / and /admin?
Your browser ui looks better than mine

2020-01-31 11:27 UTC, n2o commented
I don't see any improvement or better understanding when we add an image for each view :D the simplicity of one image is unbeatable und sufficient for the first impression of this app. I can make a new one for the Admin page, but the rest is not of interest.

2020-01-31 11:29 UTC, iTitus commented
The image is outdated

2020-01-31 11:30 UTC, n2o commented
Making a new image each time we change is string, is too much work for too little outcome.

2020-01-31 11:43 UTC, n2o commented
![shorty](https://user-images.githubusercontent.com/1507474/73536845-39a8d280-4427-11ea-855e-b7ec8a1d1c60.png)
here is a new Admin image

2020-01-31 13:36 UTC, n2o approved these changes

2020-01-31 13:36 UTC, merged